---
runtime: nodejs16
env_variables:
  PGUSER: postgres
  PGHOST: 35.231.119.33
  PGDATABASE: bg_search
  PGPASSWORD: ''
handlers:
  - url: /
    secure: always
    script: auto

  - url: /style.css
    secure: always
    static_files: public/style.css
    upload: public/style.css

  - url: /pubsub/pull
    secure: always
    script: auto

  - url: /pubsub/pull-plays
    secure: always
    script: auto

  - url: /pull-collection
    secure: always
    script: auto

  - url: /search
    secure: always
    script: auto
