---
runtime: nodejs12
handlers:
  - url: /
    secure: always
    static_files: public/index.html
    upload: public/index.html

  - url: /style.css
    secure: always
    static_files: public/style.css
    upload: public/style.css

  - url: /pubsub/pull
    secure: always
    script: auto

  - url: /pubsub/pull-plays
    secure: always
    script: auto

  - url: /search
    secure: always
    script: auto
