---
runtime: nodejs20
automatic_scaling:
  max_instances: 1
env_variables:
  PGUSER: postgres
  PGHOST: /cloudsql/bg-search:us-east1:postgres-next
  PGDATABASE: bg_search
handlers:
  - url: /style.css
    secure: always
    static_files: public/style.css
    upload: public/style.css

  - url: /light.svg
    secure: always
    static_files: public/light.svg
    upload: public/light.svg

  - url: /.*
    secure: always
    script: auto
