kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: database
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10G
  template:
    metadata:
      labels:
        app: database
    spec:
      terminationGracePeriodSeconds: 15
      volumes:
        - name: db-init-volume
          configMap:
            name: db-init
      containers:
        - name: default
          image: postgres:18.0-alpine3.22
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 6m
              memory: 92274688
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: postgres-password
          volumeMounts:
            - name: db-init-volume
              mountPath: /docker-entrypoint-initdb.d
            - name: data
              mountPath: /var/lib/postgresql
