on:
  push:
    paths:
      - Dockerfile
      - package.json
      - package-lock.json
      - shadow-cljs.edn
      - src/**
      - public/**

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - if: github.ref == 'refs/heads/master'
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ${{ env.REGISTRY}}/${{ env.IMAGE_NAME }}:${{ github.sha }}
