---
name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.16.3
        env:
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGHOST: ${{ secrets.PGHOST }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGUSER: ${{ secrets.PGUSER }}
        run: |
          npm ci
          npm t
          cat << EOF > db-credentials.json
          {
            "database": "$PGDATABASE",
            "host": "$PGHOST",
            "password": "$PGPASSWORD",
            "user": "$PGUSER"
          }
          EOF
      - uses: actions/gcloud
        with:
          args: app deploy -q -v alpha
