---
name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 10.16.3

      - run: npm ci

      - run: npm t

      - env:
          DATABASE_CREDENTIALS: ${{ secrets.DATABASE_CREDENTIALS }}
        run: echo "$DATABASE_CREDENTIALS" | base64 -d > db-credentials.json

      - uses: exelban/gcloud@v1.0.0
        env:
          PROJECT_ID: bg-search
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        with:
          args: app deploy -q -v alpha
