---
name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://node:10.16.3-alpine
        run: |
          npm ci
          npm t
      - uses: docker://google/cloud-sdk:262.0.0-alpine
        env:
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGHOST: ${{ secrets.PGHOST }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGUSER: ${{ secrets.PGUSER }}
        run: |
          cat << EOF > db-credentials.json
          {
            "database": "$PGDATABASE",
            "host": "$PGHOST",
            "password": "$PGPASSWORD",
            "user": "$PGUSER"
          }
          EOF
          gcloud app deploy -q -v alpha
